### PR TITLE
Port to 1.12.2

### PR DESCRIPTION
**Pull request by davenonymous**
Hey! I needed this (for me essential) mod to start a new 1.12 world. I hope you don't mind that I ported it myself.
Feel free to do with this whatever you want.

This is pretty direct port of the 1.11-update branch. The changes are mostly basic symbol renames, the only thing i'm not entirely sure about is the GrassColours tweak and the changes to stronghold/structure gen.

### CODE REVIEW

**Comment by Murbis1** [comment]
Cant you pls just make a own curseforge and update it there? pls?

**Comment by seven23** [comment]
Where it can be downloaded ?

**Comment by Trinsdar** [comment]
@TTFTCUTS could you merge this please or at least look at it.

**Comment by xorinzor** [comment]
really disappointing that @TTFTCUTS seems to have vanished :/

**Comment by FelixHornberger** [comment]
Somebody here who knows what the World-Type for server config?

**Pull request closed without merging**
